### ISSUE TITLE
3.2.1 version published on npm has no lib folder

### ISSUE THREAD

**Issue by vdanchenkov** [adaltas/node-csv-generate#12]
https://unpkg.com/csv-generate@3.2.1/

**Comment by wdavidw** [comment]
This is strange, I'm on it.

**Comment by wdavidw** [comment]
I just tried publishing a new 3.2.2 version and, once again, there is no lib folder. I haven't found yet what is preveting the lib folder to be published.

**Comment by muellermichel** [comment]
I assume you checked your local unix file / folder permissions?

**Comment by wdavidw** [comment]
Yes, I just published version 3.2.3, the problem was that I was declaring "./lib" and not "lib". This shall be fixed

**Comment by wdavidw** [comment]
By the way, this is kind of strange because I used "./lib" and all my other packages and it seems fine until now.
