### ISSUE TITLE
Add note that it's only for random data

### ISSUE THREAD

**Issue by Paxa** [adaltas/node-csv-generate#5]
I was looking how to simply write my data to CSV, but turns out this module only for writing random data...

Please update readme

**Comment by wdavidw** [comment]
It's in the name. Use csv-parse or csv-stringify.

**Comment by Paxa** [comment]
Can csv-parse write data?

Will it be better to call modules as `csv-parse`, `csv-write` (or `csv-generate`) and `csv-random` (or `csv-generate-random`)?

"Stringify" in my mind wasn't associated with generating CSV file, but only converting some intermediate structure into string. And "csv-generate", I assumed was to create such intermediate objects...

It wouldn't hurt to add some note to README

**Comment by samhatchett** [comment]
This was confusing to me as well; the word "generate" does not necessarily connote random generation. I must have spent ~15m here looking for an example where a csv string was "generated" from an array. Thought I was going crazy until I found the closed issues.

**Comment by etchen99** [comment]
It's like they went out the way to make things a bit hard to grok

**Comment by wdavidw** [comment]
What if in the [homepage](http://csv.adaltas.com/), instead of

> Output text, objects or Arrays

We wrote

> Generate random and user-defined texts, objects or Arrays

Or

> No input, output text, objects or Arrays

**Comment by wdavidw** [comment]
The naming is after the JSON API, CSV is a serialized string, which we parse or stringify.

**Comment by samhatchett** [comment]
of the options you list, I would prefer the second one - "Generate random and user-defined texts, objects or Arrays"

However, to be more clear, I would suggest:
Generate pseudo-random data in user-defined schemas (string, object, array).

... since none of the data is user-defined, right? It's just the format (object mode, columns, length) that can be defined.

**Comment by etchen99** [comment]
I kind of agree with Sam.  Appreciate the quick response David.

**Comment by Paxa** [comment]
Also can change code to support users’ data 🙂

**Comment by wdavidw** [comment]
To generate user data, set the columns option to an array of functions, each function returning the generated CSV field.

**Comment by Paxa** [comment]
Can you give some example?

**Comment by wdavidw** [comment]
Doc could be clarified and enriched, here is an exemple from the [column test](https://github.com/adaltas/node-csv-generate/blob/master/test/options.columns.coffee#L47-L65)

**Comment by marrs** [comment]
Another victim of this project's unique naming convention reporting in, only to add that, not only is the name of the project misleading, but even the the documentation is confused.  The first line of http://csv.adaltas.com/generate/ actually says:

> It may be used to generate random or *user driven data*.

**Comment by wdavidw** [comment]
As I wrote above:
> To generate user data, set the columns option to an array of functions, each function returning the generated CSV field.

**Comment by waynebloss** [comment]
I am thinking that the most common and obvious use-case is converting an array of objects into a CSV file and I can't find an example for that. I want something like this:

```
var myData = [{ id: 1, name: "Wayne" }, { id: 2, name: "David" }, { id: 3, name: "Sam" }];
var csvContent = convertArrayOfObjectsToCSV(myData);
// TODO: Write csvContent to a file or send it to HTTP client, etc...
```

**Comment by wdavidw** [comment]
@waynebloss Look at the [csv-stringify](https://csv.js.org/stringify/) package

**Comment by waynebloss** [comment]
@wdavidw Thanks! I  ended up choosing  json2csv  because it seemed to cover a bunch of Excel edge cases.

**Comment by gterras** [comment]
Hi late for the party but I couldn't find how the base issue has been resolved ? I have lost quite some time figuring out this package isn't really made to be used with specific data (possible but cumbersome) when a simple line in the README would make things clear.
