### ISSUE TITLE
Error when Uglify with Webpack since 2.0.0

### ISSUE THREAD

**Issue by Wifsimster** [adaltas/node-csv-generate#6]
> ERROR in build.js from UglifyJs
> Unexpected token operator «=», expected punc «,» [./node_modules/csv-generate/lib/index.js:69,0][build.js:67374,30]

index.js - Line 69 :

> Generator = function(options1 = {}) {

Roll back to @1.2.1 is working.

**Comment by wdavidw** [comment]
My bad, I forgot to update the [changelog](https://github.com/adaltas/node-csv-generate/blob/master/CHANGELOG.md). Yes, in a browser environment, you should stick with version 1.2.1.

**Comment by alimuqaddas** [comment]
No matching version found for 1.2.1.

Stuck on it extremely :(

**Comment by wdavidw** [comment]
`npm info csv-generate` => 1.1.2
