### ISSUE TITLE
Type definitions are missing for typescript

### ISSUE THREAD

**Issue by klopsknoedel** [adaltas/node-csv-generate#9]
Would be great to have a `@types/csv-generate` - package. Or better: bundled types within `csv-generate`.
I don't know why this issue got closed but it's still valid: https://github.com/adaltas/node-csv-generate/issues/7#issue-299354441

**Comment by wdavidw** [comment]
The new version 3.2.0 embed the TS definition file. Feel free to open a new issue if you find the definition incorrect or incomplete

**Comment by klopsknoedel** [comment]
That was quick. Thanks!
